--------------------------------------------------------
--  Constraints for Table AUTO_INS_LOG
--------------------------------------------------------

  ALTER TABLE "AUTO_INS_LOG" ADD CONSTRAINT "AUTO_INS_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "AUTO_INS_LOG" MODIFY ("AUTO_INS_LOG_ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "AUTO_INS_LOG" MODIFY ("XML_REQUEST" NOT NULL ENABLE);
  ALTER TABLE "AUTO_INS_LOG" MODIFY ("DATE_OPERATION" NOT NULL ENABLE);
  ALTER TABLE "AUTO_INS_LOG" MODIFY ("OPERATION_CODE" NOT NULL ENABLE);
  ALTER TABLE "AUTO_INS_LOG" MODIFY ("ENTITY_ID" NOT NULL ENABLE);
  ALTER TABLE "AUTO_INS_LOG" MODIFY ("ID" NOT NULL ENABLE);
