--------------------------------------------------------
--  DDL for Table BUSINESS_VIEW
--------------------------------------------------------

  CREATE TABLE "BUSINESS_VIEW" 
   (	"BUSINESS_VIEW_ID" NUMBER, 
	"CODE" VARCHAR2(256 BYTE), 
	"PATH" VARCHAR2(512 BYTE), 
	"SECURITY_GROUP" VARCHAR2(256 BYTE), 
	"PARENT" NUMBER, 
	"VISIBLE" NUMBER, 
	"ICON_PATH" VARCHAR2(512 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "BUSINESS_VIEW"."BUSINESS_VIEW_ID" IS 'Unique identified of business view.';
   COMMENT ON COLUMN "BUSINESS_VIEW"."CODE" IS 'Display name’s localization key.';
   COMMENT ON COLUMN "BUSINESS_VIEW"."PATH" IS 'URL.';
   COMMENT ON COLUMN "BUSINESS_VIEW"."SECURITY_GROUP" IS 'Code of security group to which the view belong (if any).';
   COMMENT ON COLUMN "BUSINESS_VIEW"."PARENT" IS 'Reference to parent element.';
   COMMENT ON COLUMN "BUSINESS_VIEW"."VISIBLE" IS 'Flag of visible business view.';
   COMMENT ON COLUMN "BUSINESS_VIEW"."ICON_PATH" IS 'Path to icon.';
   COMMENT ON TABLE "BUSINESS_VIEW"  IS 'Table stores information about business views.';
