--------------------------------------------------------
--  Constraints for Table BUSINESS_VIEW
--------------------------------------------------------

  ALTER TABLE "BUSINESS_VIEW" ADD CONSTRAINT "UK_BUSINESS_VIEW" UNIQUE ("BUSINESS_VIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "BUSINESS_VIEW" MODIFY ("VISIBLE" NOT NULL ENABLE);
  ALTER TABLE "BUSINESS_VIEW" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "BUSINESS_VIEW" MODIFY ("BUSINESS_VIEW_ID" NOT NULL ENABLE);
