--------------------------------------------------------
--  DDL for Table CONFIRMED_DIAGNOSTIC_CARD
--------------------------------------------------------

  CREATE TABLE "CONFIRMED_DIAGNOSTIC_CARD" 
   (	"ID" NUMBER, 
	"REG_NUMBER" VARCHAR2(30 BYTE), 
	"VALID_TO" DATE, 
	"VIN" VARCHAR2(50 BYTE), 
	"BODY_NUMBER" VARCHAR2(50 BYTE), 
	"CHASSIS_NUMBER" VARCHAR2(50 BYTE), 
	"PLATE_NUMBER" VARCHAR2(50 BYTE), 
	"CONFIRM_DATE" DATE, 
	"CONFIRM_BY" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
