--------------------------------------------------------
--  DDL for Table CONFIGURATION_SET
--------------------------------------------------------

  CREATE TABLE "CONFIGURATION_SET" 
   (	"CONFIGURATION_SET_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(256 BYTE), 
	"DESCRIPTION" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CONFIGURATION_SET"."CONFIGURATION_SET_ID" IS 'Unique identifier of configuration set.';
   COMMENT ON COLUMN "CONFIGURATION_SET"."NAME" IS 'Name of configuration set.';
   COMMENT ON COLUMN "CONFIGURATION_SET"."DESCRIPTION" IS 'Description of configuration set.';
   COMMENT ON TABLE "CONFIGURATION_SET"  IS 'Table stores set of component server configurations.';
