--------------------------------------------------------
--  DDL for Table CONFIGURATION_DATA
--------------------------------------------------------

  CREATE TABLE "CONFIGURATION_DATA" 
   (	"CONFIGURATION_DATA_ID" NUMBER(10,0), 
	"CONFIGURATION_PROFILE_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(256 BYTE), 
	"BODY" "XMLTYPE", 
	"SCHEME" "XMLTYPE", 
	"CHANGED" DATE, 
	"CHANGED_BY" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 XMLTYPE COLUMN "BODY" STORE AS SECUREFILE BINARY XML (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA 
 XMLTYPE COLUMN "SCHEME" STORE AS SECUREFILE BINARY XML (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;

   COMMENT ON COLUMN "CONFIGURATION_DATA"."CONFIGURATION_DATA_ID" IS 'Unique identifier for configuration data';
   COMMENT ON COLUMN "CONFIGURATION_DATA"."CONFIGURATION_PROFILE_ID" IS 'Reference on configuration profile.';
   COMMENT ON COLUMN "CONFIGURATION_DATA"."NAME" IS 'Name of configuration data.';
   COMMENT ON COLUMN "CONFIGURATION_DATA"."BODY" IS 'Configuration data in XML Document format.';
   COMMENT ON COLUMN "CONFIGURATION_DATA"."SCHEME" IS 'XML schema as XSD file.';
   COMMENT ON COLUMN "CONFIGURATION_DATA"."CHANGED" IS 'Date of last change. Must be filled with insert/update trigger.';
   COMMENT ON COLUMN "CONFIGURATION_DATA"."CHANGED_BY" IS 'User that performed last change. Must be filled with insert/update trigger.';
   COMMENT ON TABLE "CONFIGURATION_DATA"  IS 'Table stores components/subsystems configuration as XML documents. Stored documents are related to particular profile.';
