--------------------------------------------------------
--  DDL for Index CONFIRMED_DIAGNOSTIC_CARD_IDX
--------------------------------------------------------

  CREATE INDEX "CONFIRMED_DIAGNOSTIC_CARD_IDX" ON "CONFIRMED_DIAGNOSTIC_CARD" ("VIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
