--------------------------------------------------------
--  Constraints for Table CONFIGURATION_DATA
--------------------------------------------------------

  ALTER TABLE "CONFIGURATION_DATA" MODIFY ("CONFIGURATION_DATA_ID" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_DATA" MODIFY ("CONFIGURATION_PROFILE_ID" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_DATA" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_DATA" MODIFY ("CHANGED" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_DATA" MODIFY ("CHANGED_BY" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_DATA" ADD CONSTRAINT "PK_CONFIGURATION_DATA" PRIMARY KEY ("CONFIGURATION_DATA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CONFIGURATION_DATA" ADD CONSTRAINT "UK_CONFIGURATION_DATA" UNIQUE ("CONFIGURATION_PROFILE_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
