--------------------------------------------------------
--  DDL for Table CONFIRMED_DOCUMENT
--------------------------------------------------------

  CREATE TABLE "CONFIRMED_DOCUMENT" 
   (	"ID" NUMBER, 
	"DOC_TYPE_ID" NUMBER, 
	"DOC_SERIES" VARCHAR2(20 BYTE), 
	"DOC_NUMBER" VARCHAR2(20 BYTE), 
	"CONFIRM_DATE" DATE, 
	"CONFIRM_BY" VARCHAR2(200 BYTE), 
	"SCAN" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SCAN") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
