--------------------------------------------------------
--  DDL for Table CONFIGURATION_PROFILE
--------------------------------------------------------

  CREATE TABLE "CONFIGURATION_PROFILE" 
   (	"CONFIGURATION_PROFILE_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(256 BYTE), 
	"ACTIVE" NUMBER(1,0), 
	"CONFIGURATION_SET_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "CONFIGURATION_PROFILE"."CONFIGURATION_PROFILE_ID" IS 'Unique identifier of configuration profile.';
   COMMENT ON COLUMN "CONFIGURATION_PROFILE"."NAME" IS 'Name of configuration profile.';
   COMMENT ON COLUMN "CONFIGURATION_PROFILE"."ACTIVE" IS 'Flag specifying whether profile is active (1) or not (0).';
   COMMENT ON COLUMN "CONFIGURATION_PROFILE"."CONFIGURATION_SET_ID" IS 'Reference on configuration set.';
   COMMENT ON TABLE "CONFIGURATION_PROFILE"  IS 'Table stores configuration profiles related to configuration set (component server).';
