--------------------------------------------------------
--  Constraints for Table CONFIGURATION_PROFILE
--------------------------------------------------------

  ALTER TABLE "CONFIGURATION_PROFILE" ADD CONSTRAINT "UK_CONFIGURATION_PROFILE" UNIQUE ("CONFIGURATION_SET_ID", "NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CONFIGURATION_PROFILE" ADD CONSTRAINT "PK_CONFIGURATION_PROFILE" PRIMARY KEY ("CONFIGURATION_PROFILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CONFIGURATION_PROFILE" MODIFY ("CONFIGURATION_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_PROFILE" MODIFY ("ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_PROFILE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_PROFILE" MODIFY ("CONFIGURATION_PROFILE_ID" NOT NULL ENABLE);
