--------------------------------------------------------
--  Constraints for Table CONFIGURATION_SET
--------------------------------------------------------

  ALTER TABLE "CONFIGURATION_SET" ADD CONSTRAINT "UK_CONFIGURATION_SET" UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CONFIGURATION_SET" ADD CONSTRAINT "PK_CONFIGURATION_SET" PRIMARY KEY ("CONFIGURATION_SET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CONFIGURATION_SET" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_SET" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CONFIGURATION_SET" MODIFY ("CONFIGURATION_SET_ID" NOT NULL ENABLE);
