REM INSERTING into COUNTRY
SET DEFINE OFF;
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Швеция','ШВЕЦИЯ','216','SWE','752');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Швейцарская Конфедерация','ШВЕЙЦАРИЯ','217','CHE','756');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СИРИЙСКАЯ АРАБСКАЯ РЕСПУБЛИКА','218','SYR','760');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Таджикистан','ТАДЖИКИСТАН','219','TJK','762');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Таиланд','ТАИЛАНД','220','THA','764');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Тоголезская Республика','ТОГО','221','TGO','768');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ТОКЕЛАУ','222','TKL','772');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Тонга','ТОНГА','223','TON','776');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Тринидад и Тобаго','ТРИНИДАД И ТОБАГО','224','TTO','780');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ОБЪЕДИНЕННЫЕ АРАБСКИЕ ЭМИРАТЫ','225','ARE','784');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Тунисская Республика','ТУНИС','226','TUN','788');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Турецкая Республика','ТУРЦИЯ','227','TUR','792');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Туркменистан','ТУРКМЕНИЯ','228','TKM','795');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ОСТРОВА ТЕРКС И КАЙКОС','229','TCA','796');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ТУВАЛУ','230','TUV','798');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Уганда','УГАНДА','231','UGA','800');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'УКРАИНА','232','UKR','804');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'РЕСПУБЛИКА МАКЕДОНИЯ','233','MKD','807');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Арабская Республика Египет','ЕГИПЕТ','234','EGY','818');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Соединенное Королевство Великобритании и Северной Ирландии','СОЕДИНЕННОЕ КОРОЛЕВСТВО','235','GBR','826');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ГЕРНСИ','236','GGY','831');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ДЖЕРСИ','237','JEY','832');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ОСТРОВ МЭН','238','IMN','833');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Объединенная Республика Танзания','ТАНЗАНИЯ, ОБЪЕДИНЕННАЯ РЕСПУБЛИКА','239','TZA','834');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Соединенные Штаты Америки','СОЕДИНЕННЫЕ ШТАТЫ','240','USA','840');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Виргинские острова Соединенных Штатов','ВИРГИНСКИЕ ОСТРОВА, США','241','VIR','850');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'БУРКИНА-ФАСО','242','BFA','854');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Восточная Республика Уругвай','УРУГВАЙ','243','URY','858');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Узбекистан','УЗБЕКИСТАН','244','UZB','860');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Боливарианская Республика Венесуэла','ВЕНЕСУЭЛА БОЛИВАРИАНСКАЯ РЕСПУБЛИКА','245','VEN','862');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'УОЛЛИС И ФУТУНА','246','WLF','876');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Независимое Государство Самоа','САМОА','247','WSM','882');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Йеменская Республика','ЙЕМЕН','248','YEM','887');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Замбия','ЗАМБИЯ','249','ZMB','894');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Абхазия','АБХАЗИЯ','250','ABH','895');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Южная Осетия','ЮЖНАЯ ОСЕТИЯ','251','OST','896');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Переходное Исламское Государство Афганистан','АФГАНИСТАН','1','AFG','004');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Албания','АЛБАНИЯ','2','ALB','008');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'АНТАРКТИДА','3','ATA','010');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Алжирская Народная Демократическая Республика','АЛЖИР','4','DZA','012');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'АМЕРИКАНСКОЕ САМОА','5','ASM','016');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Княжество Андорра','АНДОРРА','6','AND','020');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Ангола','АНГОЛА','7','AGO','024');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'АНТИГУА И БАРБУДА','8','ATG','028');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Азербайджан','АЗЕРБАЙДЖАН','9','AZE','031');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Аргентинская Республика','АРГЕНТИНА','10','ARG','032');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'АВСТРАЛИЯ','11','AUS','036');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Австрийская Республика','АВСТРИЯ','12','AUT','040');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Содружество Багамы','БАГАМЫ','13','BHS','044');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Бахрейн','БАХРЕЙН','14','BHR','048');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Народная Республика Бангладеш','БАНГЛАДЕШ','15','BGD','050');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Армения','АРМЕНИЯ','16','ARM','051');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'БАРБАДОС','17','BRB','052');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Бельгии','БЕЛЬГИЯ','18','BEL','056');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'БЕРМУДЫ','19','BMU','060');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Бутан','БУТАН','20','BTN','064');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Многонациональное Государство Боливия','БОЛИВИЯ, МНОГОНАЦИОНАЛЬНОЕ ГОСУДАРСТВО','21','BOL','068');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'БОСНИЯ И ГЕРЦЕГОВИНА','22','BIH','070');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Ботсвана','БОТСВАНА','23','BWA','072');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ОСТРОВ БУВЕ','24','BVT','074');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Федеративная Республика Бразилия','БРАЗИЛИЯ','25','BRA','076');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'БЕЛИЗ','26','BLZ','084');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'БРИТАНСКАЯ ТЕРРИТОРИЯ В ИНДИЙСКОМ ОКЕАНЕ','27','IOT','086');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СОЛОМОНОВЫ ОСТРОВА','28','SLB','090');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Британские Виргинские острова','ВИРГИНСКИЕ ОСТРОВА, БРИТАНСКИЕ','29','VGB','092');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'БРУНЕЙ-ДАРУССАЛАМ','30','BRN','096');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Болгария','БОЛГАРИЯ','31','BGR','100');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Союза Мьянма','МЬЯНМА','32','MMR','104');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Бурунди','БУРУНДИ','33','BDI','108');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Беларусь','БЕЛАРУСЬ','34','BLR','112');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Камбоджа','КАМБОДЖА','35','KHM','116');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Камерун','КАМЕРУН','36','CMR','120');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'КАНАДА','37','CAN','124');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Кабо-Верде','КАБО-ВЕРДЕ','38','CPV','132');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ОСТРОВА КАЙМАН','39','CYM','136');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Южно-Африканская Республика','ЮЖНАЯ АФРИКА','207','ZAF','710');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Зимбабве','ЗИМБАБВЕ','208','ZWE','716');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Испания','ИСПАНИЯ','209','ESP','724');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Южный Судан','ЮЖНЫЙ СУДАН','210','SSD','728');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Судан','СУДАН','211','SDN','729');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ЦЕНТРАЛЬНО-АФРИКАНСКАЯ РЕСПУБЛИКА','40','CAF','140');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Демократическая Социалистическая Республика Шри-Ланка','ШРИ-ЛАНКА','41','LKA','144');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Чад','ЧАД','42','TCD','148');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Чили','ЧИЛИ','43','CHL','152');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Китайская Народная Республика','КИТАЙ','44','CHN','156');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ЗАПАДНАЯ САХАРА','212','ESH','732');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Суринам','СУРИНАМ','213','SUR','740');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ШПИЦБЕРГЕН И ЯН МАЙЕН','214','SJM','744');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Свазиленд','СВАЗИЛЕНД','215','SWZ','748');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ТАЙВАНЬ (КИТАЙ)','45','TWN','158');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ОСТРОВ РОЖДЕСТВА','46','CXR','162');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'КОКОСОВЫЕ (КИЛИНГ) ОСТРОВА','47','CCK','166');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Колумбия','КОЛУМБИЯ','48','COL','170');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Союз Коморы','КОМОРЫ','49','COM','174');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'МАЙОТТА','50','MYT','175');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Конго','КОНГО','51','COG','178');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Демократическая Республика Конго','КОНГО, ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА','52','COD','180');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ОСТРОВА КУКА','53','COK','184');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Коста-Рика','КОСТА-РИКА','54','CRI','188');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Хорватия','ХОРВАТИЯ','55','HRV','191');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Куба','КУБА','56','CUB','192');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Кипр','КИПР','57','CYP','196');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ЧЕШСКАЯ РЕСПУБЛИКА','58','CZE','203');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Бенин','БЕНИН','59','BEN','204');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Дания','ДАНИЯ','60','DNK','208');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Содружество Доминики','ДОМИНИКА','61','DMA','212');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ДОМИНИКАНСКАЯ РЕСПУБЛИКА','62','DOM','214');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Эквадор','ЭКВАДОР','63','ECU','218');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Эль-Сальвадор','ЭЛЬ-САЛЬВАДОР','64','SLV','222');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Экваториальная Гвинея','ЭКВАТОРИАЛЬНАЯ ГВИНЕЯ','65','GNQ','226');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Федеративная Демократическая Республика Эфиопия','ЭФИОПИЯ','66','ETH','231');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Государство Эритрея','ЭРИТРЕЯ','67','ERI','232');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Эстонская Республика','ЭСТОНИЯ','68','EST','233');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ФАРЕРСКИЕ ОСТРОВА','69','FRO','234');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ФОЛКЛЕНДСКИЕ ОСТРОВА (МАЛЬВИНСКИЕ)','70','FLK','238');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ЮЖНАЯ ДЖОРДЖИЯ И ЮЖНЫЕ САНДВИЧЕВЫ ОСТРОВА','71','SGS','239');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Фиджи','ФИДЖИ','72','FJI','242');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Финляндская Республика','ФИНЛЯНДИЯ','73','FIN','246');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ЭЛАНДСКИЕ ОСТРОВА','74','ALA','248');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Французская Республика','ФРАНЦИЯ','75','FRA','250');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ФРАНЦУЗСКАЯ ГВИАНА','76','GUF','254');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ФРАНЦУЗСКАЯ ПОЛИНЕЗИЯ','77','PYF','258');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ФРАНЦУЗСКИЕ ЮЖНЫЕ ТЕРРИТОРИИ','78','ATF','260');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Джибути','ДЖИБУТИ','79','DJI','262');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Габонская Республика','ГАБОН','80','GAB','266');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ГРУЗИЯ','81','GEO','268');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Гамбия','ГАМБИЯ','82','GMB','270');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Государство Палестина','ПАЛЕСТИНА, ГОСУДАРСТВО','83','PSE','275');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Федеративная Республика Германия','ГЕРМАНИЯ','84','DEU','276');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Гана','ГАНА','85','GHA','288');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ГИБРАЛТАР','86','GIB','292');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Кирибати','КИРИБАТИ','87','KIR','296');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Греческая Республика','ГРЕЦИЯ','88','GRC','300');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ГРЕНЛАНДИЯ','89','GRL','304');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ГРЕНАДА','90','GRD','308');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ГВАДЕЛУПА','91','GLP','312');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ГУАМ','92','GUM','316');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Гватемала','ГВАТЕМАЛА','93','GTM','320');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Гвинейская Республика','ГВИНЕЯ','94','GIN','324');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Гайана','ГАЙАНА','95','GUY','328');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Гаити','ГАИТИ','96','HTI','332');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ОСТРОВ ХЕРД И ОСТРОВА МАКДОНАЛЬД','97','HMD','334');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ПАПСКИЙ ПРЕСТОЛ (ГОСУДАРСТВО - ГОРОД ВАТИКАН)','98','VAT','336');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Гондурас','ГОНДУРАС','99','HND','340');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Специальный административный регион Китая Гонконг','ГОНКОНГ','100','HKG','344');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Венгрия','ВЕНГРИЯ','101','HUN','348');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Исландия','ИСЛАНДИЯ','102','ISL','352');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Индия','ИНДИЯ','103','IND','356');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Индонезия','ИНДОНЕЗИЯ','104','IDN','360');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Исламская Республика Иран','ИРАН, ИСЛАМСКАЯ РЕСПУБЛИКА','105','IRN','364');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Латвийская Республика','ЛАТВИЯ','123','LVA','428');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Либерия','ЛИБЕРИЯ','124','LBR','430');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Ливия','ЛИВИЯ','125','LBY','434');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Княжество Лихтенштейн','ЛИХТЕНШТЕЙН','126','LIE','438');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Литовская Республика','ЛИТВА','127','LTU','440');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Великое Герцогство Люксембург','ЛЮКСЕМБУРГ','128','LUX','442');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Специальный административный регион Китая Макао','МАКАО','129','MAC','446');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Мадагаскар','МАДАГАСКАР','130','MDG','450');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Малави','МАЛАВИ','131','MWI','454');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'МАЛАЙЗИЯ','132','MYS','458');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Мальдивская Республика','МАЛЬДИВЫ','133','MDV','462');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Мали','МАЛИ','134','MLI','466');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Мальта','МАЛЬТА','135','MLT','470');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'МАРТИНИКА','136','MTQ','474');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Исламская Республика Мавритания','МАВРИТАНИЯ','137','MRT','478');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Маврикий','МАВРИКИЙ','138','MUS','480');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Мексиканские Соединенные Штаты','МЕКСИКА','139','MEX','484');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Княжество Монако','МОНАКО','140','MCO','492');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'МОНГОЛИЯ','141','MNG','496');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Молдова','МОЛДОВА, РЕСПУБЛИКА','142','MDA','498');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ЧЕРНОГОРИЯ','143','MNE','499');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'МОНТСЕРРАТ','144','MSR','500');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Марокко','МАРОККО','145','MAR','504');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Мозамбик','МОЗАМБИК','146','MOZ','508');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Султанат Оман','ОМАН','147','OMN','512');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Намибия','НАМИБИЯ','148','NAM','516');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Науру','НАУРУ','149','NRU','520');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Федеративная Демократическая Республика Непал','НЕПАЛ','150','NPL','524');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Нидерландов','НИДЕРЛАНДЫ','151','NLD','528');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'КЮРАСАО','152','CUW','531');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'АРУБА','153','ABW','533');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СЕН-МАРТЕН (нидерландская часть)','154','SXM','534');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'БОНЭЙР, СИНТ-ЭСТАТИУС И САБА','155','BES','535');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'НОВАЯ КАЛЕДОНИЯ','156','NCL','540');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Вануату','ВАНУАТУ','157','VUT','548');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'НОВАЯ ЗЕЛАНДИЯ','158','NZL','554');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Никарагуа','НИКАРАГУА','159','NIC','558');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Нигер','НИГЕР','160','NER','562');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Федеративная Республика Нигерия','НИГЕРИЯ','161','NGA','566');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Ниуэ','НИУЭ','162','NIU','570');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ОСТРОВ НОРФОЛК','163','NFK','574');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Норвегия','НОРВЕГИЯ','164','NOR','578');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Содружество Северных Марианских островов','СЕВЕРНЫЕ МАРИАНСКИЕ ОСТРОВА','165','MNP','580');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'МАЛЫЕ ТИХООКЕАНСКИЕ ОТДАЛЕННЫЕ ОСТРОВА СОЕДИНЕННЫХ ШТАТОВ','166','UMI','581');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Федеративные штаты Микронезии','МИКРОНЕЗИЯ, ФЕДЕРАТИВНЫЕ ШТАТЫ','167','FSM','583');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Маршалловы Острова','МАРШАЛЛОВЫ ОСТРОВА','168','MHL','584');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Палау','ПАЛАУ','169','PLW','585');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Исламская Республика Пакистан','ПАКИСТАН','170','PAK','586');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Панама','ПАНАМА','171','PAN','591');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Независимое Государство Папуа Новая Гвинея','ПАПУА-НОВАЯ ГВИНЕЯ','172','PNG','598');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Парагвай','ПАРАГВАЙ','173','PRY','600');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Перу','ПЕРУ','174','PER','604');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Филиппины','ФИЛИППИНЫ','175','PHL','608');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ПИТКЕРН','176','PCN','612');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Польша','ПОЛЬША','177','POL','616');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Португальская Республика','ПОРТУГАЛИЯ','178','PRT','620');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Гвинея-Бисау','ГВИНЕЯ-БИСАУ','179','GNB','624');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Демократическая Республика Тимор-Лесте','ТИМОР-ЛЕСТЕ','180','TLS','626');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ПУЭРТО-РИКО','181','PRI','630');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Государство Катар','КАТАР','182','QAT','634');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'РЕЮНЬОН','183','REU','638');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'РУМЫНИЯ','184','ROU','642');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Российская Федерация','РОССИЯ','185','RUS','643');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Руандийская Республика','РУАНДА','186','RWA','646');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СЕН-БАРТЕЛЕМИ','187','BLM','652');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СВЯТАЯ ЕЛЕНА, ОСТРОВ ВОЗНЕСЕНИЯ, ТРИСТАН-ДА-КУНЬЯ','188','SHN','654');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СЕНТ-КИТС И НЕВИС','189','KNA','659');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'АНГИЛЬЯ','190','AIA','660');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СЕНТ-ЛЮСИЯ','191','LCA','662');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СЕН-МАРТЕН','192','MAF','663');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СЕН-ПЬЕР И МИКЕЛОН','193','SPM','666');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'СЕНТ-ВИНСЕНТ И ГРЕНАДИНЫ','194','VCT','670');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Сан-Марино','САН-МАРИНО','195','SMR','674');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Демократическая Республика Сан-Томе и Принсипи','САН-ТОМЕ И ПРИНСИПИ','196','STP','678');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Саудовская Аравия','САУДОВСКАЯ АРАВИЯ','197','SAU','682');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Сенегал','СЕНЕГАЛ','198','SEN','686');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Сербия','СЕРБИЯ','199','SRB','688');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Сейшелы','СЕЙШЕЛЫ','200','SYC','690');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Сьерра-Леоне','СЬЕРРА-ЛЕОНЕ','201','SLE','694');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Сингапур','СИНГАПУР','202','SGP','702');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Словацкая Республика','СЛОВАКИЯ','203','SVK','703');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Социалистическая Республика Вьетнам','ВЬЕТНАМ','204','VNM','704');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Ирак','ИРАК','106','IRQ','368');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ИРЛАНДИЯ','107','IRL','372');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Государство Израиль','ИЗРАИЛЬ','108','ISR','376');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Итальянская Республика','ИТАЛИЯ','109','ITA','380');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Кот д''Ивуар','КОТ Д''ИВУАР','110','CIV','384');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ЯМАЙКА','111','JAM','388');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ЯПОНИЯ','112','JPN','392');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Казахстан','КАЗАХСТАН','113','KAZ','398');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Иорданское Хашимитское Королевство','ИОРДАНИЯ','114','JOR','400');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Кения','КЕНИЯ','115','KEN','404');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Корейская Народно-Демократическая Республика','КОРЕЯ, НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА','116','PRK','408');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Корея','КОРЕЯ, РЕСПУБЛИКА','117','KOR','410');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Государство Кувейт','КУВЕЙТ','118','KWT','414');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Киргизская Республика','КИРГИЗИЯ','119','KGZ','417');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values (null,'ЛАОССКАЯ НАРОДНО-ДЕМОКРАТИЧЕСКАЯ РЕСПУБЛИКА','120','LAO','418');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Ливанская Республика','ЛИВАН','121','LBN','422');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Королевство Лесото','ЛЕСОТО','122','LSO','426');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Республика Словения','СЛОВЕНИЯ','205','SVN','705');
Insert into COUNTRY (NAME,SHORT_NAME,ID,ALPHA_CODE,NUMBER_CODE) values ('Федеративная Республика Сомали','СОМАЛИ','206','SOM','706');
