REM INSERTING into COUNTRY_BACKUP
SET DEFINE OFF;
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Австралийский Союз','Австралия','1');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Австрийская Республика','Австрия','2');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Азербайджанская Республика','Азербайджан','3');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Албания','Албания','4');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Алжирская Народная Демократическая Республика','Алжир','5');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Ангола','Ангола','6');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Княжество Андорра','Андорра','7');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Антигуа и Барбуда','Антигуа и Барбуда','8');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Аргентинская Республика','Аргентина','9');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Армения','Армения','10');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Исламская Республика Афганистан','Афганистан','11');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Содружество Багамских Островов','Багамы','12');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Народная Республика Бангладеш','Бангладеш','13');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Барбадос','Барбадос','14');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Бахрейн','Бахрейн','15');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Беларусь','Белоруссия','16');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Белиз','Белиз','17');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Бельгия','Бельгия','18');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Бенин','Бенин','19');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Болгария','Болгария','20');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Многонациональное Государство Боливия','Боливия','21');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Босния и Герцеговина','Босния и Герцеговина','22');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Ботсвана','Ботсвана','23');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Федеративная Республика Бразилия','Бразилия','24');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Государство Бруней-Даруссалам','Бруней','25');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Буркина-Фасо','Буркина-Фасо','26');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Бурунди','Бурунди','27');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Бутан','Бутан','28');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Вануату','Вануату','29');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Соединённое Королевство Великобритании и Северной Ирландии','Великобритания','30');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Венгрия','Венгрия','31');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Боливарианская Республика Венесуэла','Венесуэла','32');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Демократическая Республика Восточный Тимор','Восточный Тимор','33');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Социалистическая Республика Вьетнам','Вьетнам','34');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Габонская Республика','Габон','35');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Гаити','Гаити','36');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Кооперативная Республика Гайана','Гайана','37');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Гамбия','Гамбия','38');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Гана','Гана','39');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Гватемала','Гватемала','40');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Гвинейская Республика','Гвинея','41');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Гвинея-Бисау','Гвинея-Бисау','42');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Федеративная Республика Германия','Германия','43');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Гондурас','Гондурас','44');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Гренада','Гренада','45');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Греческая Республика','Греция','46');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Грузия','Грузия','47');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Дания','Дания','48');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Джибути','Джибути','49');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Содружество Доминики','Доминика','50');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Доминиканская Республика','Доминиканская Республика','51');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Арабская Республика Египет','Египет','52');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Замбия','Замбия','53');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Зимбабве','Зимбабве','54');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Государство Израиль','Израиль','55');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Индия','Индия','56');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Индонезия','Индонезия','57');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Иорданское Хашимитское Королевство','Иордания','58');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Ирак','Ирак','59');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Исламская Республика Иран','Иран','60');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Ирландия','Ирландия','61');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Исландия','Исландия','62');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Испания','Испания','63');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Итальянская Республика','Италия','64');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Йеменская Республика','Йемен','65');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Кабо-Верде','Кабо-Верде','66');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Казахстан','Казахстан','67');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Камбоджа','Камбоджа','68');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Камерун','Камерун','69');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Канада','Канада','70');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Государство Катар','Катар','71');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Кения','Кения','72');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Кипр','Кипр','73');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Киргизская Республика (Кыргызская Республика)','Киргизия','74');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Кирибати','Кирибати','75');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Китайская Народная Республика','КНР','76');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Колумбия','Колумбия','77');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Союз Коморских Островов','Коморы','78');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Конго','Республика Конго','79');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Демократическая Республика Конго','Демократическая Республика Конго','80');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Корейская Народно-Демократическая Республика (Северная Корея)','КНДР','81');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Корея','Республика Корея','82');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Коста-Рика','Коста-Рика','83');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Кот-д’Ивуар','Кот-д’Ивуар','84');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Куба','Куба','85');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Государство Кувейт','Кувейт','86');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Лаосская Народно-Демократическая Республика','Лаос','87');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Латвийская Республика','Латвия','88');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Лесото','Лесото','89');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Либерия','Либерия','90');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Ливанская Республика','Ливан','91');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Ливия','Ливия','92');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Литовская Республика','Литва','93');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Княжество Лихтенштейн','Лихтенштейн','94');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Великое Герцогство Люксембург','Люксембург','95');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Маврикий','Маврикий','96');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Исламская Республика Мавритания','Мавритания','97');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Мадагаскар','Мадагаскар','98');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Македония','Македония','99');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Малави','Малави','100');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Малайзия','Малайзия','101');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Мали','Мали','102');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Мальдивская Республика','Мальдивы','103');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Мальта','Мальта','104');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Марокко','Марокко','105');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Маршалловы Острова','Маршалловы Острова','106');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Мексиканские Соединенные Штаты','Мексика','107');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Мозамбик','Мозамбик','108');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Молдова','Молдавия','109');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Княжество Монако','Монако','110');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Монголия','Монголия','111');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Союз Мьянма','Мьянма','112');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Намибия','Намибия','113');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Науру','Науру','114');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Федеративная Демократическая Республика Непал','Непал','115');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Нигер','Нигер','116');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Федеративная Республика Нигерия','Нигерия','117');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Нидерландов','Нидерланды','118');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Никарагуа','Никарагуа','119');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Новая Зеландия','Новая Зеландия','120');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Норвегия','Норвегия','121');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Объединённые Арабские Эмираты','ОАЭ','122');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Султанат Оман','Оман','123');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Исламская Республика Пакистан','Пакистан','124');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Палау','Палау','125');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Панама','Панама','126');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Независимое Государство Папуа — Новая Гвинея','Папуа — Новая Гвинея','127');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Парагвай','Парагвай','128');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Перу','Перу','129');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Польша','Польша','130');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Португальская Республика','Португалия','131');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Российская Федерация','Россия','132');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Руанда','Руанда','133');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Румыния','Румыния','134');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Эль-Сальвадор','Сальвадор','135');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Независимое Государство Самоа','Самоа','136');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Сан-Марино','Сан-Марино','137');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Демократическая Республика Сан-Томе и Принсипи','Сан-Томе и Принсипи','138');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Саудовская Аравия','Саудовская Аравия','139');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Свазиленд','Свазиленд','140');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Сейшельские Острова','Сейшельские Острова','141');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Сенегал','Сенегал','142');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Сент-Винсент и Гренадины','Сент-Винсент и Гренадины','143');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Федерация Сент-Китс и Невис','Сент-Китс и Невис','144');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Сент-Люсия','Сент-Люсия','145');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Сербия','Сербия','146');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Сингапур','Сингапур','147');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Сирийская Арабская Республика','Сирия','148');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Словацкая Республика','Словакия','149');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Словения','Словения','150');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Соединённые Штаты Америки','США','151');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Соломоновы Острова','Соломоновы Острова','152');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Сомалийская Республика','Сомали','153');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Судан','Судан','154');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Суринам','Суринам','155');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Сьерра-Леоне','Сьерра-Леоне','156');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Таджикистан','Таджикистан','157');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Таиланд','Таиланд','158');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Объединённая Республика Танзания','Танзания','159');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Тоголезская Республика','Того','160');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Тонга','Тонга','161');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Тринидад и Тобаго','Тринидад и Тобаго','162');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Тувалу','Тувалу','163');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Тунисская Республика','Тунис','164');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Туркменистан','Туркмения','165');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Турецкая Республика','Турция','166');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Уганда','Уганда','167');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Узбекистан','Узбекистан','168');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Украина','Украина','169');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Восточная Республика Уругвай','Уругвай','170');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Федеративные Штаты Микронезии','Федеративные Штаты Микронезии','171');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Островов Фиджи','Фиджи','172');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Филиппины','Филиппины','173');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Финляндская Республика','Финляндия','174');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Французская Республика','Франция','175');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Хорватия','Хорватия','176');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Центральноафриканская Республика','Центральноафриканская Республика','177');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Чад','Чад','178');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Черногория','Черногория','179');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Чешская Республика','Чехия','180');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Чили','Чили','181');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Швейцарская Конфедерация','Швейцария','182');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Королевство Швеция','Швеция','183');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Демократическая Социалистическая Республика Шри-Ланка','Шри-Ланка','184');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Эквадор','Эквадор','185');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Экваториальная Гвинея','Экваториальная Гвинея','186');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Государство Эритрея','Эритрея','187');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Эстонская Республика','Эстония','188');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Федеративная Демократическая Республика Эфиопия','Эфиопия','189');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Южно-Африканская Республика','ЮАР','190');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Республика Южный Судан','Южный Судан','191');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Ямайка','Ямайка','192');
Insert into COUNTRY_BACKUP (NAME,SHORT_NAME,ID) values ('Япония','Япония','193');
