--------------------------------------------------------
--  DDL for Table DATA_LOCK_QUOTA
--------------------------------------------------------

  CREATE TABLE "DATA_LOCK_QUOTA" 
   (	"ID" NUMBER, 
	"DATE_BEGIN" DATE, 
	"DATE_END" DATE, 
	"QUOTA" NUMBER, 
	"DATA_LOCK_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
