--------------------------------------------------------
--  DDL for Package DIAGNOSTIC_CARDS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "DIAGNOSTIC_CARDS" AS 
  procedure CREATE_CONFIRMED_DIAG_CARD(
    P_REG_NUMBER IN CONFIRMED_DIAGNOSTIC_CARD.REG_NUMBER%TYPE,
    P_VALID_TO IN CONFIRMED_DIAGNOSTIC_CARD.VALID_TO%TYPE,
    P_VIN IN CONFIRMED_DIAGNOSTIC_CARD.VIN%TYPE,
    P_BODY_NUMBER IN CONFIRMED_DIAGNOSTIC_CARD.BODY_NUMBER%TYPE,
    P_CHASSIS_NUMBER IN CONFIRMED_DIAGNOSTIC_CARD.CHASSIS_NUMBER%TYPE,
    P_PLATE_NUMBER  IN CONFIRMED_DIAGNOSTIC_CARD.PLATE_NUMBER%TYPE,
    P_CONFIRM_BY IN CONFIRMED_DIAGNOSTIC_CARD.CONFIRM_BY%TYPE,
    P_ID OUT CONFIRMED_DIAGNOSTIC_CARD.ID%TYPE
  );
  
  procedure UPDATE_CONFIRMED_DIAG_CARD(
    P_ID IN CONFIRMED_DIAGNOSTIC_CARD.ID%TYPE,
    P_REG_NUMBER IN CONFIRMED_DIAGNOSTIC_CARD.REG_NUMBER%TYPE,
    P_VALID_TO IN CONFIRMED_DIAGNOSTIC_CARD.VALID_TO%TYPE,
    P_VIN IN CONFIRMED_DIAGNOSTIC_CARD.VIN%TYPE,
    P_BODY_NUMBER IN CONFIRMED_DIAGNOSTIC_CARD.BODY_NUMBER%TYPE,
    P_CHASSIS_NUMBER IN CONFIRMED_DIAGNOSTIC_CARD.CHASSIS_NUMBER%TYPE,
    P_PLATE_NUMBER  IN CONFIRMED_DIAGNOSTIC_CARD.PLATE_NUMBER%TYPE,
    P_CONFIRM_BY IN CONFIRMED_DIAGNOSTIC_CARD.CONFIRM_BY%TYPE
  );

  procedure DELETE_CONFIRMED_DIAG_CARD(
    P_ID IN CONFIRMED_DIAGNOSTIC_CARD.ID%TYPE);
    
  procedure GET_CONFIRMED_DIAG_CARDS(
    cur_out OUT sys_refcursor
  );

  procedure CHECK_CONFIRMED_DIAG_CARD(
    P_VIN IN CONFIRMED_DIAGNOSTIC_CARD.VIN%TYPE,
    P_BODY_NUMBER IN CONFIRMED_DIAGNOSTIC_CARD.BODY_NUMBER%TYPE,
    P_CHASSIS_NUMBER IN CONFIRMED_DIAGNOSTIC_CARD.CHASSIS_NUMBER%TYPE,
    P_PLATE_NUMBER  IN CONFIRMED_DIAGNOSTIC_CARD.PLATE_NUMBER%TYPE,
    CUR_OUT OUT SYS_REFCURSOR
  );
  
  procedure GET_CONFIRMED_DIAG_CARD(
    p_id CONFIRMED_DIAGNOSTIC_CARD.ID%TYPE,
    cur_out OUT sys_refcursor
  );
  
END DIAGNOSTIC_CARDS;

/
