--------------------------------------------------------
--  Constraints for Table DRIVE_PERMISSION
--------------------------------------------------------

  ALTER TABLE "DRIVE_PERMISSION" MODIFY ("LICENSE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "DRIVE_PERMISSION" MODIFY ("LICENSE_SERIAL" NOT NULL ENABLE);
  ALTER TABLE "DRIVE_PERMISSION" MODIFY ("DRIVE_FROM" NOT NULL ENABLE);
  ALTER TABLE "DRIVE_PERMISSION" MODIFY ("BIRTH_DATE" NOT NULL ENABLE);
  ALTER TABLE "DRIVE_PERMISSION" MODIFY ("SEX" NOT NULL ENABLE);
  ALTER TABLE "DRIVE_PERMISSION" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "DRIVE_PERMISSION" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "DRIVE_PERMISSION" MODIFY ("DRIVE_PERMISSION_ID" NOT NULL ENABLE);
