--------------------------------------------------------
--  Constraints for Table DRIVER
--------------------------------------------------------

  ALTER TABLE "DRIVER" MODIFY ("DRIVER_ID" NOT NULL ENABLE);
  ALTER TABLE "DRIVER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "DRIVER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "DRIVER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "DRIVER" MODIFY ("BIRTH_DATE" NOT NULL ENABLE);
  ALTER TABLE "DRIVER" MODIFY ("DRIVE_FROM" NOT NULL ENABLE);
  ALTER TABLE "DRIVER" MODIFY ("LICENSE_SERIAL" NOT NULL ENABLE);
  ALTER TABLE "DRIVER" MODIFY ("LICENSE_NUMBER" NOT NULL ENABLE);
