--------------------------------------------------------
--  Constraints for Table DRIVER_TEMP
--------------------------------------------------------

  ALTER TABLE "DRIVER_TEMP" MODIFY ("DRIVER_ID" NOT NULL ENABLE);
  ALTER TABLE "DRIVER_TEMP" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "DRIVER_TEMP" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "DRIVER_TEMP" MODIFY ("BIRTH_DATE" NOT NULL ENABLE);
  ALTER TABLE "DRIVER_TEMP" MODIFY ("DRIVE_FROM" NOT NULL ENABLE);
  ALTER TABLE "DRIVER_TEMP" MODIFY ("LICENSE_SERIAL" NOT NULL ENABLE);
  ALTER TABLE "DRIVER_TEMP" MODIFY ("LICENSE_NUMBER" NOT NULL ENABLE);
