--------------------------------------------------------
--  DDL for Table DRIVER_TEMP
--------------------------------------------------------

  CREATE TABLE "DRIVER_TEMP" 
   (	"DRIVER_ID" NUMBER, 
	"FIRST_NAME" VARCHAR2(200 BYTE), 
	"SECOND_NAME" VARCHAR2(200 BYTE), 
	"LAST_NAME" VARCHAR2(200 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"BIRTH_DATE" DATE, 
	"DRIVE_FROM" DATE, 
	"LICENSE_SERIAL" VARCHAR2(20 BYTE), 
	"LICENSE_NUMBER" VARCHAR2(20 BYTE), 
	"POLICY_ID" VARCHAR2(20 BYTE), 
	"CHECK_ID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
