--------------------------------------------------------
--  Constraints for Table FEEDBACK_PERMISSION
--------------------------------------------------------

  ALTER TABLE "FEEDBACK_PERMISSION" ADD CONSTRAINT "PK_FEEDBACK_PERMISSION" PRIMARY KEY ("FEEDBACK_PERMISSION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "FEEDBACK_PERMISSION" MODIFY ("FEEDBACK_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "FEEDBACK_PERMISSION" MODIFY ("REASON" NOT NULL ENABLE);
  ALTER TABLE "FEEDBACK_PERMISSION" MODIFY ("PERMISSION" NOT NULL ENABLE);
  ALTER TABLE "FEEDBACK_PERMISSION" MODIFY ("CREATED" NOT NULL ENABLE);
  ALTER TABLE "FEEDBACK_PERMISSION" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FEEDBACK_PERMISSION" MODIFY ("FEEDBACK_PERMISSION_ID" NOT NULL ENABLE);
